import { execFile } from 'child_process';
import { mkdtemp, rm, stat } from 'fs/promises';
import { tmpdir } from 'os';
import { join } from 'path';
import { promisify } from 'util';
import { FfmpegAdapter } from './ffmpeg.adapter';
import { FfprobeAdapter } from './ffprobe.adapter';

const execFileAsync = promisify(execFile);

/**
 * Runs against the real ffmpeg/ffprobe binaries in this container — the project
 * forbids mocking what Compose provides for real.
 *
 * Fixtures are generated by ffmpeg at setup rather than committed: binary test
 * assets in git rot silently and nobody can tell what is inside them.
 */
describe('ffprobe/ffmpeg adapters (integration)', () => {
  let workDir: string;
  let probe: FfprobeAdapter;
  let ffmpeg: FfmpegAdapter;

  const files = {
    mp4: '',
    webm: '',
    audioOnlyMp4: '',
    outsideAllowlist: '',
    trickyName: '',
  };

  beforeAll(async () => {
    workDir = await mkdtemp(join(tmpdir(), 'ffprobe-spec-'));
    probe = new FfprobeAdapter();
    ffmpeg = new FfmpegAdapter();

    const synth = (args: string[]) => execFileAsync('ffmpeg', ['-y', ...args]);

    files.mp4 = join(workDir, 'sample.mp4');
    await synth([
      '-f',
      'lavfi',
      '-i',
      'testsrc=duration=2:size=320x240:rate=10',
      '-pix_fmt',
      'yuv420p',
      files.mp4,
    ]);

    files.webm = join(workDir, 'sample.webm');
    await synth([
      '-f',
      'lavfi',
      '-i',
      'testsrc=duration=2:size=320x240:rate=10',
      files.webm,
    ]);

    // Accepted container, but no video track — TD-09's second rejection.
    files.audioOnlyMp4 = join(workDir, 'audio-only.mp4');
    await synth([
      '-f',
      'lavfi',
      '-i',
      'sine=frequency=440:duration=2',
      '-c:a',
      'aac',
      files.audioOnlyMp4,
    ]);

    // Container outside the allowlist — TD-09's first rejection.
    files.outsideAllowlist = join(workDir, 'sample.avi');
    await synth([
      '-f',
      'lavfi',
      '-i',
      'testsrc=duration=1:size=160x120:rate=10',
      files.outsideAllowlist,
    ]);

    // A filename that would be catastrophic if it ever reached a shell.
    files.trickyName = join(workDir, 'evil; touch pwned.mp4 $(id).mp4');
    await synth([
      '-f',
      'lavfi',
      '-i',
      'testsrc=duration=1:size=160x120:rate=10',
      '-pix_fmt',
      'yuv420p',
      files.trickyName,
    ]);
  }, 120000);

  afterAll(async () => {
    await rm(workDir, { recursive: true, force: true });
  });

  describe('FfprobeAdapter', () => {
    it('should read the eight metadata fields from a real mp4', async () => {
      const metadata = await probe.probe(files.mp4);

      expect(metadata.format_name).toContain('mp4');
      expect(metadata.duration_seconds).toBe(2);
      expect(metadata.width).toBe(320);
      expect(metadata.height).toBe(240);
      expect(metadata.video_codec).toBeTruthy();
      expect(metadata.size_bytes).toBeGreaterThan(0);
      expect(metadata.bitrate).toBeGreaterThan(0);
      expect(metadata.hasVideoStream).toBe(true);
    });

    it('should read a real webm through the same path', async () => {
      const metadata = await probe.probe(files.webm);

      expect(metadata.format_name).toContain('webm');
      expect(metadata.width).toBe(320);
      expect(metadata.hasVideoStream).toBe(true);
    });

    it('should report no video stream for an audio-only mp4', async () => {
      const metadata = await probe.probe(files.audioOnlyMp4);

      // The container is accepted; the file still is not a video.
      expect(metadata.format_name).toContain('mp4');
      expect(metadata.hasVideoStream).toBe(false);
      expect(metadata.audio_codec).toBeTruthy();
    });

    it('should report a container outside the allowlist as-is', async () => {
      const metadata = await probe.probe(files.outsideAllowlist);

      expect(metadata.format_name).toContain('avi');
      expect(metadata.format_name).not.toContain('mp4');
    });

    it('should treat a shell-hostile filename as data, never as a command', async () => {
      // If the path were interpolated into a shell string, `; touch` and
      // `$(id)` would execute. execFile with an argument array spawns no shell.
      const metadata = await probe.probe(files.trickyName);

      expect(metadata.hasVideoStream).toBe(true);
      // The side effect the injection would have produced never happened.
      await expect(stat(join(workDir, 'pwned.mp4'))).rejects.toThrow();
    });
  });

  describe('FfmpegAdapter', () => {
    it('should produce a readable jpeg from a real mp4', async () => {
      const output = join(workDir, 'thumb-mp4.jpg');

      await ffmpeg.extractThumbnail(files.mp4, output, 2);

      const info = await stat(output);
      expect(info.size).toBeGreaterThan(0);

      // Round-trip through ffprobe: a truncated or invalid jpeg would not
      // report as an image here.
      const probed = await probe.probe(output);
      expect(probed.format_name).toContain('image2');
      expect(probed.width).toBe(640);
    });

    it('should still produce a frame for a clip shorter than the seek point', async () => {
      const short = join(workDir, 'short.mp4');
      await execFileAsync('ffmpeg', [
        '-y',
        '-f',
        'lavfi',
        '-i',
        'testsrc=duration=0.4:size=160x120:rate=10',
        '-pix_fmt',
        'yuv420p',
        short,
      ]);
      const output = join(workDir, 'thumb-short.jpg');

      // Seeking to the fixed 1s point would land past the end and write
      // nothing; the adapter clamps to the middle of the clip instead.
      await ffmpeg.extractThumbnail(short, output, 0);

      const info = await stat(output);
      expect(info.size).toBeGreaterThan(0);
    }, 30000);
  });
});
